// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tmSTp4sEZSUn4K52S4J5Cc
// Component: LUHUSpECu9
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tmSTp4sEZSUn4K52S4J5Cc/projectcss
import * as sty from "./PlasmicLoginScreenIcon.module.css"; // plasmic-import: LUHUSpECu9/css

import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: ocFti_1wZw/icon

export type PlasmicLoginScreenIcon__VariantMembers = {};

export type PlasmicLoginScreenIcon__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginScreenIcon__VariantsArgs;
export const PlasmicLoginScreenIcon__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLoginScreenIcon__ArgsType = {};
type ArgPropType = keyof PlasmicLoginScreenIcon__ArgsType;
export const PlasmicLoginScreenIcon__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginScreenIcon__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  logoWhite012?: p.Flex<"div">;
};

export interface DefaultLoginScreenIconProps {
  className?: string;
}

function PlasmicLoginScreenIcon__RenderFunc(props: {
  variants: PlasmicLoginScreenIcon__VariantsArgs;
  args: PlasmicLoginScreenIcon__ArgsType;
  overrides: PlasmicLoginScreenIcon__OverridesType;
  dataFetches?: PlasmicLoginScreenIcon__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Ellipse1Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"logoWhite012"}
        data-plasmic-override={overrides.logoWhite012}
        className={classNames(defaultcss.all, sty.logoWhite012)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "logoWhite012"],
  svg: ["svg"],
  logoWhite012: ["logoWhite012"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  logoWhite012: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginScreenIcon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginScreenIcon__VariantsArgs;
    args?: PlasmicLoginScreenIcon__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLoginScreenIcon__Fetches;
  } & Omit<PlasmicLoginScreenIcon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLoginScreenIcon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginScreenIcon__ArgProps,
      internalVariantPropNames: PlasmicLoginScreenIcon__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLoginScreenIcon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginScreenIcon";
  } else {
    func.displayName = `PlasmicLoginScreenIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginScreenIcon = Object.assign(
  // Top-level PlasmicLoginScreenIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    logoWhite012: makeNodeComponent("logoWhite012"),

    // Metadata about props expected for PlasmicLoginScreenIcon
    internalVariantProps: PlasmicLoginScreenIcon__VariantProps,
    internalArgProps: PlasmicLoginScreenIcon__ArgProps
  }
);

export default PlasmicLoginScreenIcon;
/* prettier-ignore-end */
