// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tmSTp4sEZSUn4K52S4J5Cc
// Component: CdGBKX-GF3
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tmSTp4sEZSUn4K52S4J5Cc/projectcss
import * as sty from "./PlasmicInfoText.module.css"; // plasmic-import: CdGBKX-GF3/css

export type PlasmicInfoText__VariantMembers = {};

export type PlasmicInfoText__VariantsArgs = {};
type VariantPropType = keyof PlasmicInfoText__VariantsArgs;
export const PlasmicInfoText__VariantProps = new Array<VariantPropType>();

export type PlasmicInfoText__ArgsType = {};
type ArgPropType = keyof PlasmicInfoText__ArgsType;
export const PlasmicInfoText__ArgProps = new Array<ArgPropType>();

export type PlasmicInfoText__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultInfoTextProps {
  className?: string;
}

function PlasmicInfoText__RenderFunc(props: {
  variants: PlasmicInfoText__VariantsArgs;
  args: PlasmicInfoText__ArgsType;
  overrides: PlasmicInfoText__OverridesType;
  dataFetches?: PlasmicInfoText__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Add your kickass username"}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInfoText__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInfoText__VariantsArgs;
    args?: PlasmicInfoText__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicInfoText__Fetches;
  } & Omit<PlasmicInfoText__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicInfoText__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInfoText__ArgProps,
      internalVariantPropNames: PlasmicInfoText__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicInfoText__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInfoText";
  } else {
    func.displayName = `PlasmicInfoText.${nodeName}`;
  }
  return func;
}

export const PlasmicInfoText = Object.assign(
  // Top-level PlasmicInfoText renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicInfoText
    internalVariantProps: PlasmicInfoText__VariantProps,
    internalArgProps: PlasmicInfoText__ArgProps
  }
);

export default PlasmicInfoText;
/* prettier-ignore-end */
