// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tmSTp4sEZSUn4K52S4J5Cc
// Component: 3cVUvuSuaX
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tmSTp4sEZSUn4K52S4J5Cc/projectcss
import * as sty from "./PlasmicLoginScreenUsername.module.css"; // plasmic-import: 3cVUvuSuaX/css

export type PlasmicLoginScreenUsername__VariantMembers = {};

export type PlasmicLoginScreenUsername__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginScreenUsername__VariantsArgs;
export const PlasmicLoginScreenUsername__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLoginScreenUsername__ArgsType = {};
type ArgPropType = keyof PlasmicLoginScreenUsername__ArgsType;
export const PlasmicLoginScreenUsername__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginScreenUsername__OverridesType = {
  root?: p.Flex<"div">;
  rectangle26?: p.Flex<"div">;
  small?: p.Flex<"div">;
  small2?: p.Flex<"div">;
};

export interface DefaultLoginScreenUsernameProps {
  className?: string;
}

function PlasmicLoginScreenUsername__RenderFunc(props: {
  variants: PlasmicLoginScreenUsername__VariantsArgs;
  args: PlasmicLoginScreenUsername__ArgsType;
  overrides: PlasmicLoginScreenUsername__OverridesType;
  dataFetches?: PlasmicLoginScreenUsername__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"rectangle26"}
        data-plasmic-override={overrides.rectangle26}
        className={classNames(defaultcss.all, sty.rectangle26)}
      />

      <div
        data-plasmic-name={"small"}
        data-plasmic-override={overrides.small}
        className={classNames(defaultcss.all, sty.small)}
      >
        <div
          data-plasmic-name={"small2"}
          data-plasmic-override={overrides.small2}
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.small2
          )}
        >
          {"Username"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "rectangle26", "small", "small2"],
  rectangle26: ["rectangle26"],
  small: ["small", "small2"],
  small2: ["small2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  rectangle26: "div";
  small: "div";
  small2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginScreenUsername__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginScreenUsername__VariantsArgs;
    args?: PlasmicLoginScreenUsername__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLoginScreenUsername__Fetches;
  } & Omit<PlasmicLoginScreenUsername__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLoginScreenUsername__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginScreenUsername__ArgProps,
      internalVariantPropNames: PlasmicLoginScreenUsername__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLoginScreenUsername__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginScreenUsername";
  } else {
    func.displayName = `PlasmicLoginScreenUsername.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginScreenUsername = Object.assign(
  // Top-level PlasmicLoginScreenUsername renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    rectangle26: makeNodeComponent("rectangle26"),
    small: makeNodeComponent("small"),
    small2: makeNodeComponent("small2"),

    // Metadata about props expected for PlasmicLoginScreenUsername
    internalVariantProps: PlasmicLoginScreenUsername__VariantProps,
    internalArgProps: PlasmicLoginScreenUsername__ArgProps
  }
);

export default PlasmicLoginScreenUsername;
/* prettier-ignore-end */
