// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tmSTp4sEZSUn4K52S4J5Cc
// Component: MJcMq4T9I0
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tmSTp4sEZSUn4K52S4J5Cc/projectcss
import * as sty from "./PlasmicUsernameShuriken.module.css"; // plasmic-import: MJcMq4T9I0/css

import ellipse135LjtNoo4Ya from "./images/ellipse13.svg"; // plasmic-import: 5ljtNoo4ya/picture

export type PlasmicUsernameShuriken__VariantMembers = {};

export type PlasmicUsernameShuriken__VariantsArgs = {};
type VariantPropType = keyof PlasmicUsernameShuriken__VariantsArgs;
export const PlasmicUsernameShuriken__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUsernameShuriken__ArgsType = {};
type ArgPropType = keyof PlasmicUsernameShuriken__ArgsType;
export const PlasmicUsernameShuriken__ArgProps = new Array<ArgPropType>();

export type PlasmicUsernameShuriken__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<"img">;
  shurikenB051?: p.Flex<"div">;
};

export interface DefaultUsernameShurikenProps {
  className?: string;
}

function PlasmicUsernameShuriken__RenderFunc(props: {
  variants: PlasmicUsernameShuriken__VariantsArgs;
  args: PlasmicUsernameShuriken__ArgsType;
  overrides: PlasmicUsernameShuriken__OverridesType;
  dataFetches?: PlasmicUsernameShuriken__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <img
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(defaultcss.img, sty.img)}
        role={"img"}
        src={ellipse135LjtNoo4Ya}
      />

      <div
        data-plasmic-name={"shurikenB051"}
        data-plasmic-override={overrides.shurikenB051}
        className={classNames(defaultcss.all, sty.shurikenB051)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "shurikenB051"],
  img: ["img"],
  shurikenB051: ["shurikenB051"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: "img";
  shurikenB051: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUsernameShuriken__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUsernameShuriken__VariantsArgs;
    args?: PlasmicUsernameShuriken__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicUsernameShuriken__Fetches;
  } & Omit<PlasmicUsernameShuriken__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUsernameShuriken__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUsernameShuriken__ArgProps,
      internalVariantPropNames: PlasmicUsernameShuriken__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicUsernameShuriken__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUsernameShuriken";
  } else {
    func.displayName = `PlasmicUsernameShuriken.${nodeName}`;
  }
  return func;
}

export const PlasmicUsernameShuriken = Object.assign(
  // Top-level PlasmicUsernameShuriken renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    shurikenB051: makeNodeComponent("shurikenB051"),

    // Metadata about props expected for PlasmicUsernameShuriken
    internalVariantProps: PlasmicUsernameShuriken__VariantProps,
    internalArgProps: PlasmicUsernameShuriken__ArgProps
  }
);

export default PlasmicUsernameShuriken;
/* prettier-ignore-end */
