// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tmSTp4sEZSUn4K52S4J5Cc
// Component: hD6c_JkoI2
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import UsernameShuriken from "../../UsernameShuriken"; // plasmic-import: MJcMq4T9I0/component
import InfoText from "../../InfoText"; // plasmic-import: CdGBKX-GF3/component
import InfoText2 from "../../InfoText2"; // plasmic-import: qVl3P7-CbV/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tmSTp4sEZSUn4K52S4J5Cc/projectcss
import * as sty from "./PlasmicLoginInfoCard.module.css"; // plasmic-import: hD6c_JkoI2/css

export type PlasmicLoginInfoCard__VariantMembers = {};

export type PlasmicLoginInfoCard__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginInfoCard__VariantsArgs;
export const PlasmicLoginInfoCard__VariantProps = new Array<VariantPropType>();

export type PlasmicLoginInfoCard__ArgsType = {};
type ArgPropType = keyof PlasmicLoginInfoCard__ArgsType;
export const PlasmicLoginInfoCard__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginInfoCard__OverridesType = {
  root?: p.Flex<"div">;
  usernameShuriken?: p.Flex<typeof UsernameShuriken>;
  infoText?: p.Flex<typeof InfoText>;
  infoText2?: p.Flex<typeof InfoText2>;
};

export interface DefaultLoginInfoCardProps {
  className?: string;
}

function PlasmicLoginInfoCard__RenderFunc(props: {
  variants: PlasmicLoginInfoCard__VariantsArgs;
  args: PlasmicLoginInfoCard__ArgsType;
  overrides: PlasmicLoginInfoCard__OverridesType;
  dataFetches?: PlasmicLoginInfoCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <UsernameShuriken
        data-plasmic-name={"usernameShuriken"}
        data-plasmic-override={overrides.usernameShuriken}
        className={classNames("__wab_instance", sty.usernameShuriken)}
      />

      <InfoText
        data-plasmic-name={"infoText"}
        data-plasmic-override={overrides.infoText}
        className={classNames("__wab_instance", sty.infoText)}
      />

      <InfoText2
        data-plasmic-name={"infoText2"}
        data-plasmic-override={overrides.infoText2}
        className={classNames("__wab_instance", sty.infoText2)}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "usernameShuriken", "infoText", "infoText2"],
  usernameShuriken: ["usernameShuriken"],
  infoText: ["infoText"],
  infoText2: ["infoText2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  usernameShuriken: typeof UsernameShuriken;
  infoText: typeof InfoText;
  infoText2: typeof InfoText2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginInfoCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginInfoCard__VariantsArgs;
    args?: PlasmicLoginInfoCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLoginInfoCard__Fetches;
  } & Omit<PlasmicLoginInfoCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLoginInfoCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginInfoCard__ArgProps,
      internalVariantPropNames: PlasmicLoginInfoCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLoginInfoCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginInfoCard";
  } else {
    func.displayName = `PlasmicLoginInfoCard.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginInfoCard = Object.assign(
  // Top-level PlasmicLoginInfoCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    usernameShuriken: makeNodeComponent("usernameShuriken"),
    infoText: makeNodeComponent("infoText"),
    infoText2: makeNodeComponent("infoText2"),

    // Metadata about props expected for PlasmicLoginInfoCard
    internalVariantProps: PlasmicLoginInfoCard__VariantProps,
    internalArgProps: PlasmicLoginInfoCard__ArgProps
  }
);

export default PlasmicLoginInfoCard;
/* prettier-ignore-end */
