// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tmSTp4sEZSUn4K52S4J5Cc
// Component: X6r6xnnRXH
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tmSTp4sEZSUn4K52S4J5Cc/projectcss
import * as sty from "./PlasmicLoginScreenFirstName.module.css"; // plasmic-import: X6r6xnnRXH/css

export type PlasmicLoginScreenFirstName__VariantMembers = {};

export type PlasmicLoginScreenFirstName__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginScreenFirstName__VariantsArgs;
export const PlasmicLoginScreenFirstName__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLoginScreenFirstName__ArgsType = {};
type ArgPropType = keyof PlasmicLoginScreenFirstName__ArgsType;
export const PlasmicLoginScreenFirstName__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginScreenFirstName__OverridesType = {
  root?: p.Flex<"div">;
  rectangle25?: p.Flex<"div">;
  firstName?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultLoginScreenFirstNameProps {
  className?: string;
}

function PlasmicLoginScreenFirstName__RenderFunc(props: {
  variants: PlasmicLoginScreenFirstName__VariantsArgs;
  args: PlasmicLoginScreenFirstName__ArgsType;
  overrides: PlasmicLoginScreenFirstName__OverridesType;
  dataFetches?: PlasmicLoginScreenFirstName__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"rectangle25"}
        data-plasmic-override={overrides.rectangle25}
        className={classNames(defaultcss.all, sty.rectangle25)}
      />

      <div
        data-plasmic-name={"firstName"}
        data-plasmic-override={overrides.firstName}
        className={classNames(defaultcss.all, sty.firstName)}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox
          )}
        >
          {"First Name"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "rectangle25", "firstName", "freeBox"],
  rectangle25: ["rectangle25"],
  firstName: ["firstName", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  rectangle25: "div";
  firstName: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginScreenFirstName__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginScreenFirstName__VariantsArgs;
    args?: PlasmicLoginScreenFirstName__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLoginScreenFirstName__Fetches;
  } & Omit<PlasmicLoginScreenFirstName__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLoginScreenFirstName__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginScreenFirstName__ArgProps,
      internalVariantPropNames: PlasmicLoginScreenFirstName__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLoginScreenFirstName__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginScreenFirstName";
  } else {
    func.displayName = `PlasmicLoginScreenFirstName.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginScreenFirstName = Object.assign(
  // Top-level PlasmicLoginScreenFirstName renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    rectangle25: makeNodeComponent("rectangle25"),
    firstName: makeNodeComponent("firstName"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicLoginScreenFirstName
    internalVariantProps: PlasmicLoginScreenFirstName__VariantProps,
    internalArgProps: PlasmicLoginScreenFirstName__ArgProps
  }
);

export default PlasmicLoginScreenFirstName;
/* prettier-ignore-end */
